name: demo_widgets
description: A new Flutter project.
version: 0.0.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/yohom/demo_widgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decorated_flutter: ^0.12.0+1
  permission_handler: ^4.4.0+hotfix.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: