name: demo_widgets
description: A new Flutter project.
version: 0.4.1
homepage: https://github.com/yohom/demo_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  decorated_flutter: ^0.28.1
  flutter_syntax_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter